const JuegosH = [
    {
        TituloEspañol: "Ascenso de la maquinaria",
        TituloOriginal: "Soaring of machinarie",
        TituloRespaldo: "",
        Imagen: "../img/content/SoaringOfMachinariae.webp",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    },
    {
        TituloEspañol: "Adventure LOG (ALOG)",
        TituloOriginal: "",
        TituloRespaldo: "",
        Imagen: "img/imagenJuego.png",
        DireccionImagen: "https://chatgpt.com/",
        Descripcion1: "Este es un juego de aventura",
        Descripcion2: "Ambientado en la cultura medieval",
        Descripcion3: "Posee multiples finales",
        Autor: "Autor 1",
        Motor: "Unity",
        Contraseña: "1234",
        Tags: ["Aventura", "Acción"],
        EnlaceDescarga1: "https://www.juego1.com/descarga",
        EnlaceDescarga2: "https://www.juego1.com/descarga",
        EnlaceDescarga3: "https://www.juego1.com/descarga"
    }
];

/*
\n
*/

